[package]
name = "wrenched"
version = "0.1.0"
edition = "2021"

[dependencies]
ropey = "1.6"
crop = { version = "0.4", features = ["graphemes"] }
vello = "0.3"
winit = "0.30"
xilem = { git = "https://github.com/linebender/xilem", rev = "1eaff8f0fd75cb42436b4265a2262023a94fffdd" }
masonry = { git = "https://github.com/linebender/xilem", rev = "1eaff8f0fd75cb42436b4265a2262023a94fffdd" }
accesskit = "0.17"
tracing = "0.1"
parley = { git = "https://github.com/linebender/parley", rev = "c0d158b5d77c5726ed33fd3f2cbfcde95df374ef", features = ["accesskit"] }
eyre = "0.6"
smallvec = "1.13"
color-backtrace = { version = "0.6", default-features = false }
tracing-subscriber = "0.3"
peniko = "0.2"
kurbo = "0.11"
rand = "0.8.5"
fontique = "0.2.0"

[[bin]]
name = "wrenched"
path = "app/main.rs"
